[project]
name = "julia-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rlopc4ds", email = "rlopc4ds@gmail.com" }
]
requires-python = ">=3.11,<3.12"
dependencies = [
    "azure-functions>=1.21.3",
    "fastapi[all]>=0.115.11",
]

[project.scripts]
check-api = "api:check_package"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/api"]
